language: generic # don't install any environment
language: node_js
node_js:
- stable
branches:
  except:
    - gh-pages
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git checkout -b gh-pages
    git merge master
    git config --global push.default simple
    npm run compile-stylus
    git add .
    git -c user.name='travis' -c user.email='travis' commit --allow-empty -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push --set-upstream origin gh-pages -f -q &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
